version: "3.4"

services:
  app:
    image: docker-node-mongo-redis
    volumes:
      - ./:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
  
  db:
    image: mongo
    volumes:
      - .docker/data/db:/data/db
    restart: unless-stopped
  
  redis: # for Bull queue
    image: redis:5-alpine
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped
 